import { getServerSession } from "next-auth"
import { authOptions } from "@/lib/auth"
import { redirect } from "next/navigation"
import { FileText, Users, Building, Calendar } from "lucide-react"
import { ReportActions } from "@/components/dashboard/reports/ReportActions"
import { getAutomatedReports } from "@/app/actions/automatedReports"
import { DownloadPdfButton } from "@/components/dashboard/reports/DownloadPdfButton"

export default async function AutomatedReportingPage() {
    const session = await getServerSession(authOptions)
    if (!session?.user || !['SECTOR_ADMIN', 'CELL_ADMIN', 'VILLAGE_LEADER'].includes(session.user.role)) {
        redirect("/dashboard")
    }

    const reports = await getAutomatedReports()
    const latestReport = reports.length > 0 ? reports[0] : null

    const todayString = new Date().toLocaleDateString('en-RW', { dateStyle: 'long' })

    const protocolLevel = session.user.role === 'SECTOR_ADMIN' ? 'SECTOR' :
        session.user.role === 'CELL_ADMIN' ? 'CELL' : 'VILLAGE'

    return (
        <div className="space-y-8 max-w-5xl mx-auto pb-20">
            <div className="flex items-center justify-between no-print">
                <div className="flex flex-col gap-1">
                    <h1 className="text-2xl font-bold text-slate-800">Automated System Reports</h1>
                    <p className="text-slate-500">Official performance analysis generated by system chronometer.</p>
                </div>
                <ReportActions />
            </div>

            <div className="bg-white p-12 rounded-2xl shadow-sm border border-slate-100 space-y-12 print:shadow-none print:border-none">
                {/* Report Header */}
                <div className="flex items-start justify-between border-b pb-8 border-slate-100">
                    <div className="flex items-center gap-3">
                        <div className="w-12 h-12 bg-primary rounded-lg flex items-center justify-center text-white">
                            <FileText className="w-7 h-7" />
                        </div>
                        <div>
                            <h2 className="text-xl font-black text-slate-900 leading-tight">NIBOYE {protocolLevel} PROTOCOL</h2>
                            <p className="text-sm font-bold text-primary tracking-widest uppercase">FPR Management System</p>
                        </div>
                    </div>
                    <div className="text-right">
                        <p className="text-xs font-bold text-slate-400 uppercase tracking-widest">Date Viewed</p>
                        <p className="text-sm font-bold text-slate-800">{todayString}</p>
                    </div>
                </div>

                {/* Latest Executive Summary */}
                <section className="space-y-4">
                    <h3 className="text-sm font-black text-slate-400 uppercase tracking-[0.2em]">01. Latest Executive Summary</h3>
                    {latestReport ? (
                        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                            <div className="p-6 bg-slate-50 rounded-xl border border-slate-100">
                                <p className="text-xs font-bold text-slate-400 uppercase mb-2">Total Membership</p>
                                <div className="flex items-center gap-2">
                                    <Users className="w-5 h-5 text-primary" />
                                    <span className="text-2xl font-black text-slate-800">{latestReport.metrics.totalMembers.toLocaleString()}</span>
                                </div>
                            </div>
                            <div className="p-6 bg-slate-50 rounded-xl border border-slate-100">
                                <p className="text-xs font-bold text-slate-400 uppercase mb-2">Activities Held</p>
                                <div className="flex items-center gap-2">
                                    <Calendar className="w-5 h-5 text-primary" />
                                    <span className="text-2xl font-black text-slate-800">{latestReport.metrics.totalActivities.toLocaleString()}</span>
                                </div>
                            </div>
                            <div className="p-6 bg-slate-50 rounded-xl border border-slate-100">
                                <p className="text-xs font-bold text-slate-400 uppercase mb-2">Attendance Participation</p>
                                <div className="flex items-center gap-2">
                                    <Building className="w-5 h-5 text-primary" />
                                    <span className="text-2xl font-black text-primary">{(latestReport.metrics.totalAttendance || 0).toLocaleString()} Marks</span>
                                </div>
                            </div>
                            {latestReport.metrics.totalContributions !== undefined && (
                                <div className="p-6 bg-green-50 rounded-xl border border-green-100 md:col-span-3">
                                    <p className="text-xs font-bold text-green-600 uppercase mb-2">Total Contributions Collected</p>
                                    <div className="flex items-center gap-2">
                                        <Building className="w-5 h-5 text-green-600" />
                                        <span className="text-2xl font-black text-green-700">{latestReport.metrics.totalContributions.toLocaleString()} RWF</span>
                                    </div>
                                </div>
                            )}
                        </div>
                    ) : (
                        <div className="p-6 text-center text-slate-500 bg-slate-50 rounded-xl">No reports generated yet. Run the cron job to see data.</div>
                    )}
                </section>

                {/* Report Archive List */}
                <section className="space-y-4 pt-4 border-t">
                    <h3 className="text-sm font-black text-slate-400 uppercase tracking-[0.2em]">02. Report Archives</h3>
                    <div className="overflow-hidden border border-slate-100 rounded-xl">
                        <table className="w-full text-left text-sm">
                            <thead className="bg-slate-50 text-slate-500 font-bold uppercase text-[10px] tracking-wider">
                                <tr>
                                    <th className="px-6 py-4">Generation Date</th>
                                    <th className="px-6 py-4">Scope</th>
                                    <th className="px-6 py-4">Frequency</th>
                                    <th className="px-6 py-4">Total Members</th>
                                    <th className="px-6 py-4">Status</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-slate-100">
                                {reports.length === 0 ? (
                                    <tr>
                                        <td colSpan={5} className="px-6 py-8 text-center text-slate-500 font-medium">
                                            Archive is currently empty.
                                        </td>
                                    </tr>
                                ) : (
                                    reports.map(r => (
                                        <tr key={r.id}>
                                            <td className="px-6 py-4 font-bold text-slate-700">{new Date(r.date).toLocaleDateString()}</td>
                                            <td className="px-6 py-4">{r.scopeName} ({r.level})</td>
                                            <td className="px-6 py-4">
                                                <span className="capitalize">{r.frequency}</span>
                                            </td>
                                            <td className="px-6 py-4 font-semibold">{r.metrics.totalMembers}</td>
                                            <td className="px-6 py-4">
                                                <DownloadPdfButton report={r} />
                                            </td>
                                        </tr>
                                    ))
                                )}
                            </tbody>
                        </table>
                    </div>
                </section>

                {/* Footer */}
                <div className="pt-12 border-t border-slate-100 flex items-center justify-between">
                    <div className="text-[10px] text-slate-400 leading-relaxed max-w-sm">
                        This is an automated system-generated document suite. Maintained by cron services in Niboye backend.
                    </div>
                    <div className="text-right">
                        <div className="w-32 h-12 border-b border-slate-300 ml-auto mb-2"></div>
                        <p className="text-[10px] font-bold text-slate-400 uppercase">System Integrity Check</p>
                    </div>
                </div>
            </div>
        </div>
    )
}
